services:
    backend:
        container_name: Backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        environment:
            SPRING_PROFILES_ACTIVE: docker
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME:-86400000}
            CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN:-http://localhost:4200}

    frontend:
        container_name: Frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend

