services:
    traefik:
        image: traefik:v3.0
        container_name: traefik
        restart: unless-stopped
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
            - "--certificatesresolvers.letsencrypt.acme.email=robin.fantino.rf@gmail.com"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"  # Dashboard Traefik
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./letsencrypt:/letsencrypt"
        networks:
            - proxy

    backend:
        container_name: Backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        networks:
            - proxy
        environment:
            SPRING_PROFILES_ACTIVE: docker
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: ${DB_NAME}
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME:-86400000}
            CORS_ALLOWED_ORIGIN: ${CORS_ALLOWED_ORIGIN:-http://localhost:4200}
        depends_on:
            db:
                condition: service_healthy
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.backend.rule=Host(`api.stockofrigo.huntcraft.fr`)"
            - "traefik.http.routers.backend.entrypoints=websecure"
            - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
            # --- IMPORTANT ---
            # Indique à Traefik que ton app Spring Boot tourne sur le port 8080 
            # à l'intérieur de son conteneur.
            - "traefik.http.services.backend.loadbalancer.server.port=8080"
            # Pas besoin d'exposer de 'ports:' ici, Traefik s'en charge.
    
    frontend:
        container_name: Frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        depends_on:
            - backend
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            # Le domaine principal
            - "traefik.http.routers.frontend.rule=Host(`stockofrigo.huntcraft.fr`)"
            - "traefik.http.routers.frontend.entrypoints=websecure"
            - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
            # Nginx sert les fichiers statiques sur le port 80 par défaut
            - "traefik.http.services.frontend.loadbalancer.server.port=80"


    db:
        container_name: stocko_frigo_db
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u${DB_USER} -p${DB_PASSWORD} --silent']
            interval: 5s
            timeout: 5s
            retries: 20
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - proxy

    # adminer:
    #     image: adminer:latest
    #     restart: always
    #     networks:
    #         - proxy
    #     labels:
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.adminer.rule=Host(`adminer.stockofrigo.huntcraft.fr`)"
    #         - "traefik.http.routers.adminer.entrypoints=websecure"
    #         - "traefik.http.routers.adminer.tls.certresolver=letsencrypt"
    #         - "traefik.http.services.adminer.loadbalancer.server.port=8080"

volumes:
    db-data:

networks:
    proxy:
        driver: bridge
